name: Hprofile Actions Test
on: workflow_dispatch
jobs:
  Testing:
    runs-on: ubuntu-latest
    steps:
      - name: Code checkout
        uses: actions/checkout@v4"

      - name: Maven test
        uses: mvn test
      
      - name: Checkstyle
        run: mvn checkstyle:checkstyle
         

